### ISSUE TITLE
request

### ISSUE THREAD

**Issue by carl1961** [polihedron/TM1637_Timer_RPM-stepper_motor#1]
Great program, I'm using it for a tesla coil unwinder ( when a coil wind goes bad) right now I just long press to stop motor.
https://rumble.com/v4y38a9-tesla-coil-winding-and-unwinding-machine.html

would it be possible for you to do a version with no timer, and click on encoder button to stop and start? I tried to remove timer, but can't get the code to work.

**Comment by polihedron** [comment]
added new branch:
https://github.com/polihedron/TM1637_Timer_RPM-stepper_motor/tree/tesla-coil-unwinder

check the code on your device, should be working as you wrote: 
no timer and button on encoder starts and stops motor.

**Comment by carl1961** [comment]
@polihedron  Works Perfect! Thanks so much.

**Comment by polihedron** [comment]
good.
